import type { Agent, Department } from "../../types/department";
import { AGENT_TYPES } from "../../data/constants";

export const API_URL = "/api/chat";

export const SYSTEM_PROMPT = `You are an expert in institutional operations, knowledge work analysis, and AI transformation strategy. Your specialty is mapping how organizations actually function — the real flows of work, information, and sensory data — and identifying where AI can create the most leverage.

You must respond ONLY with a single valid JSON object. No markdown, no explanation, no backticks. Pure JSON.

Schema:
{
  "label": "string — short department name",
  "icon": "string — single emoji",
  "color": "string — hex color",
  "accent": "string — slightly darker hex",
  "summary": "string — 2-3 sentences: scale, operational facts, primary pain points with real stats",
  "region": "string — country/region context",
  "infrastructure": "string — one of: high-bandwidth | mobile-first | limited-connectivity | mixed",
  "valueChain": ["string — full flow from intake to outcome"],
  "roles": [{ "id":"snake_case", "label":"Role Title", "icon":"emoji", "x":number_10_to_90, "y":number_15_to_85 }],
  "workflows": [{ "id":"w1", "from":"role_id", "to":"role_id", "label":"what flows", "type":"knowledge|physical", "aiImpact":"high|medium|low", "valueFlow":"valueCreate|costSink|valueLeak|riskNode" }],
  "sensors": [{ "id":"s1", "role":"role_id", "sense":"sight|sound|smell|touch", "label":"what is perceived", "detail":"specific signals", "aiNote":"concrete AI capability with real systems/studies", "icon":"emoji" }],
  "knowledgeWork": [{ "id":"k1", "role":"role_id", "label":"task name", "effort":1_to_10, "frequency":"string", "aiImpact":"supercharge|shortcircuit", "aiNote":"specific AI transformation with real tools/data", "costPerYear":"string", "valueAtStake":"string" }],
  "agents": [{ "id":"a1", "name":"Agent Name", "type":"web|mobile|edge|orch", "taskIds":["k1","s1"], "trigger":"what activates", "output":"what it produces", "humanInLoop":"when human reviews", "integrations":["system1","api2"], "priority":1_to_5, "complexity":"low|medium|high", "mobileFirst":boolean }]
}

Rules:
- roles: 4-6 roles, spread across SVG canvas (x:10-90, y:15-85, no clustering)
- workflows: 5-8 flows between roles
- sensors: 4-7 sensory touchpoints
- knowledgeWork: 6-10 tasks, highest-effort + highest-AI-leverage work
- agents: 4-7 agents, priority 1=build first
- For African/Global South: weight mobile agents, note connectivity constraints, reference local context
- Be specific: name real tools, studies, statistics
- All role ids in workflows/sensors/knowledgeWork must exist in the roles array`;

export function buildSystemPrompt(agent: Agent, dept: Department): string {
  const at = AGENT_TYPES[agent.type] || AGENT_TYPES.web;
  const kw = (agent.taskIds||[]).map(id => (dept.knowledgeWork||[]).find(k=>k.id===id)).filter(Boolean);
  const sens = (agent.taskIds||[]).map(id => (dept.sensors||[]).find(s=>s.id===id)).filter(Boolean);

  const taskBlock = kw.map(k =>
    `- ${k!.label} (${k!.aiImpact === "supercharge" ? "AI-amplified, human reviews" : "AI-autonomous, human handles exceptions"})
   What you know: ${k!.aiNote}
   Economic context: ${k!.costPerYear||"unknown cost"} / Value at stake: ${k!.valueAtStake||"high"}`
  ).join("\n");

  const sensorBlock = sens.map(s =>
    `- ${s!.label} (${s!.sense} sense): ${s!.detail}. AI capability: ${s!.aiNote}`
  ).join("\n");

  return `You are ${agent.name}, an AI agent deployed in a ${dept.label}.

INSTITUTIONAL CONTEXT:
${dept.summary}

YOUR DEPLOYMENT TYPE: ${at.label}
${at.desc}

YOUR TRIGGER: ${agent.trigger}
YOUR OUTPUT: ${agent.output}
HUMAN-IN-LOOP PROTOCOL: ${agent.humanInLoop || "None — you operate autonomously"}
INTEGRATIONS YOU WORK WITH: ${(agent.integrations||[]).join(", ") || "None specified"}
${dept.infrastructure ? `INFRASTRUCTURE CONTEXT: ${dept.infrastructure}` : ""}

TASKS YOU HANDLE:
${taskBlock || "General institutional workflows"}

${sensorBlock ? `SENSORY / DATA INPUTS YOU PROCESS:\n${sensorBlock}` : ""}

BEHAVIOR RULES:
1. Stay in character as ${agent.name}. Do not break from this role.
2. When given inputs matching your trigger, produce output in the format described above.
3. When human review is required per your protocol, explicitly flag it: "⚠️ HUMAN REVIEW NEEDED: [reason]"
4. Use mock/placeholder data when real integrations aren't available — clearly label as [MOCK DATA].
5. Be specific and operational. Do not give generic AI responses. You are a specialized institutional agent.
6. If asked to demonstrate your capabilities, walk through a realistic example scenario for this institution type.
7. Be concise. Institutional agents deliver structured outputs, not essays.`;
}

export function buildScaffold(agent: Agent, dept: Department, systemPrompt: string): string {
  return `// ${agent.name} — Next.js API Route
// Auto-generated by DEPT.OS from agent spec
// Department: ${dept.label}
// Agent type: ${agent.type} | Priority: P${agent.priority} | Complexity: ${agent.complexity}
//
// INTEGRATIONS TO WIRE:
${(agent.integrations||[]).map(i => `//   - ${i}`).join("\n")}

import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

// System prompt (auto-generated from DEPT.OS spec):
const SYSTEM_PROMPT = \`${systemPrompt.replace(/`/g, "\\`")}\`;

export async function POST(req) {
  const { input } = await req.json();

  // TODO: Fetch real data from integrations before calling the model
  // const integrationData = await fetchFromIntegrations(input);

  const response = await client.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1024,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: input,
        // TODO: Augment with integration data:
        // content: \\\`\\\${input}\\nContext from integrations:\\n\\\${JSON.stringify(integrationData)}\\\`
      }
    ]
  });

  return Response.json({
    output: response.content[0].text,
    agent: "${agent.name}",
    requiresHumanReview: response.content[0].text.includes("⚠️ HUMAN REVIEW NEEDED"),
  });
}`;
}
